[project]
name = "problem_set_4"
version = "1.0.0"
description = "RSA"
authors = [{ name = "Louis641214" }]
dependencies = [
    "matplotlib>=3.10"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]